
.globl fabs_ppc
fabs_ppc:
pc_adjust 0x4
ret

.globl fabsRC_ppc
fabsRC_ppc:
pc_adjust 0x4
ret

.globl fadd_ppc
fadd_ppc:
pc_adjust 0x4
ret

.globl faddRC_ppc
faddRC_ppc:
pc_adjust 0x4
ret

.globl fadds_ppc
fadds_ppc:
pc_adjust 0x4
ret

.globl faddsRC_ppc
faddsRC_ppc:
pc_adjust 0x4
ret

.globl fcmpo_ppc
fcmpo_ppc:
pc_adjust 0x4
ret

.globl fcmpu_ppc
fcmpu_ppc:
pc_adjust 0x4
ret

.globl fctiw_ppc
fctiw_ppc:
pc_adjust 0x4
ret

.globl fctiwRC_ppc
fctiwRC_ppc:
pc_adjust 0x4
ret

.globl fctiwz_ppc
fctiwz_ppc:
pc_adjust 0x4
ret

.globl fctiwzRC_ppc
fctiwzRC_ppc:
pc_adjust 0x4
ret

.globl fdiv_ppc
fdiv_ppc:
pc_adjust 0x4
ret

.globl fdivRC_ppc
fdivRC_ppc:
pc_adjust 0x4
ret

.globl fdivs_ppc
fdivs_ppc:
pc_adjust 0x4
ret

.globl fdivsRC_ppc
fdivsRC_ppc:
pc_adjust 0x4
ret

.globl fmadd_ppc
fmadd_ppc:
pc_adjust 0x4
ret

.globl fmaddRC_ppc
fmaddRC_ppc:
pc_adjust 0x4
ret

.globl fmadds_ppc
fmadds_ppc:
pc_adjust 0x4
ret

.globl fmaddsRC_ppc
fmaddsRC_ppc:
pc_adjust 0x4
ret

.globl fmr_ppc
fmr_ppc:
pc_adjust 0x4
ret

.globl fmrRC_ppc
fmrRC_ppc:
pc_adjust 0x4
ret

.globl fmsub_ppc
fmsub_ppc:
pc_adjust 0x4
ret

.globl fmsubRC_ppc
fmsubRC_ppc:
pc_adjust 0x4
ret

.globl fmsubs_ppc
fmsubs_ppc:
pc_adjust 0x4
ret

.globl fmsubsRC_ppc
fmsubsRC_ppc:
pc_adjust 0x4
ret

.globl fmul_ppc
fmul_ppc:
pc_adjust 0x4
ret

.globl fmulRC_ppc
fmulRC_ppc:
pc_adjust 0x4
ret

.globl fmuls_ppc
fmuls_ppc:
pc_adjust 0x4
ret

.globl fmulsRC_ppc
fmulsRC_ppc:
pc_adjust 0x4
ret

.globl fnabs_ppc
fnabs_ppc:
pc_adjust 0x4
ret

.globl fnabsRC_ppc
fnabsRC_ppc:
pc_adjust 0x4
ret

.globl fneg_ppc
fneg_ppc:
pc_adjust 0x4
ret

.globl fnegRC_ppc
fnegRC_ppc:
pc_adjust 0x4
ret

.globl fnmadd_ppc
fnmadd_ppc:
pc_adjust 0x4
ret

.globl fnmaddRC_ppc
fnmaddRC_ppc:
pc_adjust 0x4
ret

.globl fnmadds_ppc
fnmadds_ppc:
pc_adjust 0x4
ret

.globl fnmaddsRC_ppc
fnmaddsRC_ppc:
pc_adjust 0x4
ret

.globl fnmsub_ppc
fnmsub_ppc:
pc_adjust 0x4
ret

.globl fnmsubRC_ppc
fnmsubRC_ppc:
pc_adjust 0x4
ret

.globl fnmsubs_ppc
fnmsubs_ppc:
pc_adjust 0x4
ret

.globl fnmsubsRC_ppc
fnmsubsRC_ppc:
pc_adjust 0x4
ret

.globl fres_ppc
fres_ppc:
pc_adjust 0x4
ret

.globl fresRC_ppc
fresRC_ppc:
pc_adjust 0x4
ret

.globl frsp_ppc
frsp_ppc:
pc_adjust 0x4
ret

.globl frspRC_ppc
frspRC_ppc:
pc_adjust 0x4
ret

.globl frsqrte_ppc
frsqrte_ppc:
pc_adjust 0x4
ret

.globl frsqrteRC_ppc
frsqrteRC_ppc:
pc_adjust 0x4
ret

.globl fsel_ppc
fsel_ppc:
pc_adjust 0x4
ret

.globl fselRC_ppc
fselRC_ppc:
pc_adjust 0x4
ret

.globl fsub_ppc
fsub_ppc:
pc_adjust 0x4
ret

.globl fsubRC_ppc
fsubRC_ppc:
pc_adjust 0x4
ret

.globl fsubs_ppc
fsubs_ppc:
pc_adjust 0x4
ret

.globl fsubsRC_ppc
fsubsRC_ppc:
pc_adjust 0x4
ret

