.globl lbz_ppc
lbz_ppc:

.globl lbzu_ppc
lbzu_ppc:

.globl lbzux_ppc
lbzux_ppc:

.globl lbzx_ppc
lbzx_ppc:

.globl lha_ppc
lha_ppc:

.globl lhau_ppc
lhau_ppc:

.globl lhaux_ppc
lhaux_ppc:

.globl lhax_ppc
lhax_ppc:

.globl lhbrx_ppc
lhbrx_ppc:

.globl lhz_ppc
lhz_ppc:

.globl lhzu_ppc
lhzu_ppc:

.globl lhzux_ppc
lhzux_ppc:

.globl lhzx_ppc
lhzx_ppc:

.globl lmw_ppc
lmw_ppc:

.globl lswi_ppc
lswi_ppc:

.globl lswx_ppc
lswx_ppc:

.globl lwarx_ppc
lwarx_ppc:

.globl lwbrx_ppc
lwbrx_ppc:

.globl lwz_ppc
lwz_ppc:

.globl lwzu_ppc
lwzu_ppc:

.globl lwzux_ppc
lwzux_ppc:

.globl lwzx_ppc
lwzx_ppc:
