
.globl dcbf_ppc
dcbf_ppc:
pc_adjust 0x4
ret

.globl dcbi_ppc
dcbi_ppc:
pc_adjust 0x4
ret

.globl dcbst_ppc
dcbst_ppc:
pc_adjust 0x4
ret

.globl dcbt_ppc
dcbt_ppc:
pc_adjust 0x4
ret

.globl dcbtst_ppc
dcbtst_ppc:
pc_adjust 0x4
ret

.globl dcbz_ppc
dcbz_ppc:
pc_adjust 0x4
ret

.globl dcbz_l_ppc
dcbz_l_ppc:
pc_adjust 0x4
ret

.globl eciwx_ppc
eciwx_ppc:
pc_adjust 0x4
ret

.globl ecowx_ppc
ecowx_ppc:
pc_adjust 0x4
ret

.globl eieio_ppc
eieio_ppc:
pc_adjust 0x4
ret

