.globl psq_l_ppc
psq_l_ppc:

.globl psq_lu_ppc
psq_lu_ppc:

.globl psq_lux_ppc
psq_lux_ppc:

.globl psq_lx_ppc
psq_lx_ppc:

.globl psq_st_ppc
psq_st_ppc:

.globl psq_stu_ppc
psq_stu_ppc:

.globl psq_stux_ppc
psq_stux_ppc:

.globl psq_stx_ppc
psq_stx_ppc:

.globl ps_abs_ppc
ps_abs_ppc:

.globl ps_absRC_ppc
ps_absRC_ppc:

.globl ps_add_ppc
ps_add_ppc:

.globl ps_addRC_ppc
ps_addRC_ppc:

.globl ps_cmpo0_ppc
ps_cmpo0_ppc:

.globl ps_cmpo1_ppc
ps_cmpo1_ppc:

.globl ps_cmpu0_ppc
ps_cmpu0_ppc:

.globl ps_cmpu1_ppc
ps_cmpu1_ppc:

.globl ps_div_ppc
ps_div_ppc:

.globl ps_divRC_ppc
ps_divRC_ppc:

.globl ps_madd_ppc
ps_madd_ppc:

.globl ps_maddRC_ppc
ps_maddRC_ppc:

.globl ps_madds0_ppc
ps_madds0_ppc:

.globl ps_madds0RC_ppc
ps_madds0RC_ppc:

.globl ps_madds1_ppc
ps_madds1_ppc:

.globl ps_madds1RC_ppc
ps_madds1RC_ppc:

.globl ps_merge00_ppc
ps_merge00_ppc:

.globl ps_merge00RC_ppc
ps_merge00RC_ppc:

.globl ps_merge01_ppc
ps_merge01_ppc:

.globl ps_merge01RC_ppc
ps_merge01RC_ppc:

.globl ps_merge10_ppc
ps_merge10_ppc:

.globl ps_merge10RC_ppc
ps_merge10RC_ppc:

.globl ps_merge11_ppc
ps_merge11_ppc:

.globl ps_merge11RC_ppc
ps_merge11RC_ppc:

.globl ps_mr_ppc
ps_mr_ppc:

.globl ps_mrRC_ppc
ps_mrRC_ppc:

.globl ps_msub_ppc
ps_msub_ppc:

.globl ps_msubRC_ppc
ps_msubRC_ppc:

.globl ps_mul_ppc
ps_mul_ppc:

.globl ps_mulRC_ppc
ps_mulRC_ppc:

.globl ps_muls0_ppc
ps_muls0_ppc:

.globl ps_muls0RC_ppc
ps_muls0RC_ppc:

.globl ps_muls1_ppc
ps_muls1_ppc:

.globl ps_muls1RC_ppc
ps_muls1RC_ppc:

.globl ps_nabs_ppc
ps_nabs_ppc:

.globl ps_nabsRC_ppc
ps_nabsRC_ppc:

.globl ps_neg_ppc
ps_neg_ppc:

.globl ps_negRC_ppc
ps_negRC_ppc:

.globl ps_nmadd_ppc
ps_nmadd_ppc:

.globl ps_nmaddRC_ppc
ps_nmaddRC_ppc:

.globl ps_nmsub_ppc
ps_nmsub_ppc:

.globl ps_nmsubRC_ppc
ps_nmsubRC_ppc:

.globl ps_res_ppc
ps_res_ppc:

.globl ps_resRC_ppc
ps_resRC_ppc:

.globl ps_rsqrte_ppc
ps_rsqrte_ppc:

.globl ps_rsqrteRC_ppc
ps_rsqrteRC_ppc:

.globl ps_sel_ppc
ps_sel_ppc:

.globl ps_selRC_ppc
ps_selRC_ppc:

.globl ps_sub_ppc
ps_sub_ppc:

.globl ps_subRC_ppc
ps_subRC_ppc:

.globl ps_sum0_ppc
ps_sum0_ppc:

.globl ps_sum0RC_ppc
ps_sum0RC_ppc:

.globl ps_sum1_ppc
ps_sum1_ppc:

.globl ps_sum1RC_ppc
ps_sum1RC_ppc:

