.globl rlwimi_ppc
rlwimi_ppc:
pc_adjust 0x4
ret

.globl rlwimiRC_ppc
rlwimiRC_ppc:
pc_adjust 0x4
ret

.globl rlwinm_ppc
rlwinm_ppc:
pc_adjust 0x4
ret

.globl rlwinmRC_ppc
rlwinmRC_ppc:
pc_adjust 0x4
ret

.globl rlwnm_ppc
rlwnm_ppc:
pc_adjust 0x4
ret

.globl rlwnmRC_ppc
rlwnmRC_ppc:
pc_adjust 0x4
ret

.globl slw_ppc
slw_ppc:
pc_adjust 0x4
ret

.globl slwRC_ppc
slwRC_ppc:
pc_adjust 0x4
ret

.globl sraw_ppc
sraw_ppc:
pc_adjust 0x4
ret

.globl srawRC_ppc
srawRC_ppc:
pc_adjust 0x4
ret

.globl srawi_ppc
srawi_ppc:
pc_adjust 0x4
ret

.globl srawiRC_ppc
srawiRC_ppc:
pc_adjust 0x4
ret

.globl srw_ppc
srw_ppc:
pc_adjust 0x4
ret

.globl srwRC_ppc
srwRC_ppc:
pc_adjust 0x4
ret

