.globl rlwimi_ppc
rlwimi_ppc:

.globl rlwimiRC_ppc
rlwimiRC_ppc:

.globl rlwinm_ppc
rlwinm_ppc:

.globl rlwinmRC_ppc
rlwinmRC_ppc:

.globl rlwnm_ppc
rlwnm_ppc:

.globl rlwnmRC_ppc
rlwnmRC_ppc:

.globl slw_ppc
slw_ppc:

.globl slwRC_ppc
slwRC_ppc:

.globl sraw_ppc
sraw_ppc:

.globl srawRC_ppc
srawRC_ppc:

.globl srawi_ppc
srawi_ppc:

.globl srawiRC_ppc
srawiRC_ppc:

.globl srw_ppc
srw_ppc:

.globl srwRC_ppc
srwRC_ppc:

