.globl stfd_ppc
stfd_ppc:
pc_adjust 0x4
ret

.globl stfdu_ppc
stfdu_ppc:
pc_adjust 0x4
ret

.globl stfdux_ppc
stfdux_ppc:
pc_adjust 0x4
ret

.globl stfdx_ppc
stfdx_ppc:
pc_adjust 0x4
ret

.globl stfiwx_ppc
stfiwx_ppc:
pc_adjust 0x4
ret

.globl stfs_ppc
stfs_ppc:
pc_adjust 0x4
ret

.globl stfsu_ppc
stfsu_ppc:
pc_adjust 0x4
ret

.globl stfsux_ppc
stfsux_ppc:
pc_adjust 0x4
ret

.globl stfsx_ppc
stfsx_ppc:
pc_adjust 0x4
ret

