.globl stb_ppc
stb_ppc:
pc_adjust 0x4
ret

.globl stbu_ppc
stbu_ppc:
pc_adjust 0x4
ret

.globl stbux_ppc
stbux_ppc:
pc_adjust 0x4
ret

.globl stbx_ppc
stbx_ppc:
pc_adjust 0x4
ret

.globl sth_ppc
sth_ppc:
pc_adjust 0x4
ret

.globl sthbrx_ppc
sthbrx_ppc:
pc_adjust 0x4
ret

.globl sthu_ppc
sthu_ppc:
pc_adjust 0x4
ret

.globl sthux_ppc
sthux_ppc:
pc_adjust 0x4
ret

.globl sthx_ppc
sthx_ppc:
pc_adjust 0x4
ret

.globl stmw_ppc
stmw_ppc:
pc_adjust 0x4
ret

.globl stswi_ppc
stswi_ppc:
pc_adjust 0x4
ret

.globl stswx_ppc
stswx_ppc:
pc_adjust 0x4
ret

.globl stw_ppc
stw_ppc:
pc_adjust 0x4
ret

.globl stwbrx_ppc
stwbrx_ppc:
pc_adjust 0x4
ret

.globl stwcxRC_ppc
stwcxRC_ppc:
pc_adjust 0x4
ret

.globl stwu_ppc
stwu_ppc:
pc_adjust 0x4
ret

.globl stwux_ppc
stwux_ppc:
pc_adjust 0x4
ret

.globl stwx_ppc
stwx_ppc:
pc_adjust 0x4
ret

